"""Generate the OpenAPI document for the Kōan REST API from the live Flask app.

The document is **derived** from the app's route table and request metadata
attached to registered views. Auth requirements come from the ``require_token``
decorator marker (``_koan_requires_token``), not a hand-maintained allow-list.

Usage::

    python -m app.api.openapi_gen --output openapi.yaml   # (re)generate
    python -m app.api.openapi_gen --check --output openapi.yaml  # fail on drift

Generation needs no running server, no API token, and no ``api.enabled: true``.
See specs/005-openapi-enforcement/ and docs/operations/rest-api.md.
"""

import argparse
import re
import sys
from copy import deepcopy
from pathlib import Path

import yaml
from flask import Flask

from app.api.openapi_metadata import (
    MCP_ENABLED_ATTR,
    QUERY_PARAMETERS_ATTR,
    REQUEST_REQUIRED_ATTR,
    REQUEST_SCHEMA_ATTR,
)

# The API contract version (matches the /v1 URL prefix). Pinned deliberately so
# that bumping app.__version__ on a release does NOT cause spurious spec drift.
API_VERSION = "1.0.0"
OPENAPI_VERSION = "3.1.0"

DEFAULT_OUTPUT = "openapi.yaml"

_HEADER = (
    "# Kōan REST API — OpenAPI specification.\n"
    "# GENERATED by `make openapi` (app.api.openapi_gen) — do not edit by hand.\n"
    "# Regenerate and commit after adding/removing/modifying an API endpoint.\n"
)

# Werkzeug methods that Flask injects automatically and that are not part of the
# documented contract.
_IGNORED_METHODS = {"HEAD", "OPTIONS"}

# Flask's built-in static endpoint is not part of the REST API.
_IGNORED_ENDPOINTS = {"static"}

# Introspection cannot observe the HTTP status a handler returns. Record the
# known non-200 successes here; everything else defaults to 200.
# KEEP IN SYNC: this is the one hand-maintained map in the generator — a route
# that starts returning 201/202 without an entry here will be documented as 200
# and nothing will flag it. `test_openapi_gen.test_known_success_codes_declared`
# guards the entries below; add both the entry and its assertion together.
SUCCESS_STATUS = {
    ("post", "/v1/missions"): "202",
    ("post", "/v1/projects"): "201",
}

# One-line human summary per API tag (blueprint / command group). Feeds the
# OpenAPI ``tags[].description``, which the CLI surfaces as group-level --help.
# This is the single source for group help — keep each entry a short sentence.
TAG_DESCRIPTIONS = {
    "admin": "Config, pause/resume, restart, update and shutdown",
    "health": "Liveness probe (no token required)",
    "missions": "Queue, inspect, reorder and delete missions",
    "observability": "Logs, metrics and usage",
    "projects": "List, add, update and remove watched projects",
    "status": "Current agent state, execution and mission counters",
}

_PATH_PARAM_RE = re.compile(r"<(?:[^:<>]+:)?([^<>]+)>")


def _openapi_path(rule: str) -> str:
    """Convert a Werkzeug rule (``/v1/x/<conv:id>``) to OpenAPI form (``/v1/x/{id}``)."""
    return _PATH_PARAM_RE.sub(r"{\1}", rule)


def _path_params(openapi_path: str) -> list:
    """Build OpenAPI parameter objects for each ``{name}`` in the path."""
    names = re.findall(r"{([^{}]+)}", openapi_path)
    return [
        {
            "name": name,
            "in": "path",
            "required": True,
            "schema": {"type": "string"},
        }
        for name in names
    ]


def _summary(view) -> str:
    """First non-empty line of the view's docstring (fallback: humanized name)."""
    doc = (view.__doc__ or "").strip()
    if doc:
        return doc.splitlines()[0].strip()
    return view.__name__.replace("_", " ").strip().capitalize()


def _tag(endpoint: str) -> str:
    """Blueprint name (segment before the first dot); the inline route uses its own name."""
    return endpoint.split(".")[0]


def build_spec(app: Flask) -> dict:
    """Build the OpenAPI 3.1 document (as a plain dict) from ``app``'s route table.

    Pure with respect to registered routes and their attached metadata.
    """
    paths: dict = {}
    tags: set = set()

    for rule in app.url_map.iter_rules():
        if rule.endpoint in _IGNORED_ENDPOINTS:
            continue
        methods = sorted((rule.methods or set()) - _IGNORED_METHODS)
        if not methods:
            continue

        openapi_path = _openapi_path(rule.rule)
        view = app.view_functions[rule.endpoint]
        secured = bool(getattr(view, "_koan_requires_token", False))
        tag = _tag(rule.endpoint)
        tags.add(tag)
        path_params = _path_params(openapi_path)
        query_params = getattr(view, QUERY_PARAMETERS_ATTR, ())
        request_schema = getattr(view, REQUEST_SCHEMA_ATTR, None)

        for method in methods:
            m = method.lower()
            success = SUCCESS_STATUS.get((m, openapi_path), "200")
            responses = {success: {"description": "Successful response"}}
            if secured:
                responses["401"] = _error_response("Missing or malformed bearer token")
                responses["403"] = _error_response("Invalid bearer token")
            responses["default"] = _error_response("Error response")

            operation = {
                # Method-qualified so a future multi-method view cannot emit two
                # operations sharing an operationId (which is invalid OpenAPI).
                "operationId": f"{rule.endpoint}_{m}".replace(".", "_"),
                "summary": _summary(view),
                "tags": [tag],
                "responses": responses,
            }
            if getattr(view, MCP_ENABLED_ATTR, False):
                operation["x-koan-mcp"] = True
            parameters = [*deepcopy(path_params), *deepcopy(query_params)]
            if parameters:
                operation["parameters"] = parameters
            if request_schema is not None:
                operation["requestBody"] = {
                    "required": bool(getattr(view, REQUEST_REQUIRED_ATTR, True)),
                    "content": {
                        "application/json": {
                            "schema": deepcopy(request_schema),
                        },
                    },
                }
            if not secured:
                # Override the global bearerAuth requirement — this route is public.
                operation["security"] = []

            paths.setdefault(openapi_path, {})[m] = operation

    sorted_tags = sorted(tags)
    return {
        "openapi": OPENAPI_VERSION,
        "info": {
            "title": "Kōan REST API",
            "version": API_VERSION,
            "description": (
                "Optional, token-authenticated HTTP control layer for the Kōan agent. "
                "See docs/operations/rest-api.md."
            ),
        },
        "servers": [{"url": "http://127.0.0.1:8420", "description": "Default loopback bind"}],
        "security": [{"bearerAuth": []}],
        "tags": [
            (
                {"name": t, "description": TAG_DESCRIPTIONS[t]}
                if t in TAG_DESCRIPTIONS
                else {"name": t}
            )
            for t in sorted_tags
        ],
        "paths": paths,
        "components": {
            "securitySchemes": {
                "bearerAuth": {"type": "http", "scheme": "bearer"},
            },
            "schemas": {
                "Error": {
                    "type": "object",
                    "required": ["error"],
                    "properties": {
                        "error": {
                            "type": "object",
                            "required": ["code", "message"],
                            "properties": {
                                "code": {"type": "string"},
                                "message": {"type": "string"},
                            },
                        },
                    },
                },
            },
        },
    }


def _error_response(description: str) -> dict:
    return {
        "description": description,
        "content": {
            "application/json": {"schema": {"$ref": "#/components/schemas/Error"}},
        },
    }


def dump_yaml(spec: dict) -> str:
    """Serialize the spec to canonical, deterministic YAML (stable across runs).

    ``width`` is set effectively-infinite so PyYAML never line-folds a long
    scalar. Folding position is width- and version-sensitive, so allowing it
    would make the byte-diff drift gate flap between PyYAML/Python versions
    (e.g. dev vs CI). Disabling wrapping removes that variable entirely.
    """
    body = yaml.safe_dump(
        spec,
        sort_keys=True,
        default_flow_style=False,
        allow_unicode=True,
        width=1 << 30,
    )
    return _HEADER + body


def render() -> str:
    """Return the canonical OpenAPI YAML text for the current API.

    Builds the app in a throwaway temp ``koan_root`` (auto-removed) so generation
    never binds a port, reads a token, or pollutes the working tree.
    """
    import tempfile

    from app.api import create_app
    from app.utils import koan_tmp_dir

    # Scratch dir lives under the per-uid koan_tmp_dir() (koan/CLAUDE.md temp-file
    # rule). koan_tmp_dir() fails closed if it can't secure the dir; let that
    # propagate rather than silently writing scratch files to a bare /tmp path.
    with tempfile.TemporaryDirectory(prefix="koan-openapi-", dir=koan_tmp_dir()) as tmp:
        tmp_root = Path(tmp)
        app = create_app(koan_root=tmp_root, instance_dir=tmp_root / "instance")
        return dump_yaml(build_spec(app))


def generate(output_path: Path) -> None:
    """Write the OpenAPI document to ``output_path``."""
    output_path.write_text(render(), encoding="utf-8")


def _drift_instruction(output_path: Path) -> str:
    return (
        f"ERROR: {output_path} is out of date with the REST API code.\n"
        "Regenerate and commit it:\n"
        "    make openapi\n"
        "    git add koan/openapi.yaml && git commit\n"
    )


def check(output_path: Path) -> int:
    """Return 0 if ``output_path`` matches freshly-generated output, else 1.

    On mismatch (or a missing file) prints an actionable fix instruction to stderr.
    """
    current = render()
    try:
        committed = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        committed = None
    if committed == current:
        return 0
    sys.stderr.write(_drift_instruction(output_path))
    return 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m app.api.openapi_gen",
        description="Generate or check the Kōan REST API OpenAPI document.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Path to the OpenAPI document (default: {DEFAULT_OUTPUT}).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the document is out of date (does not write).",
    )
    args = parser.parse_args(argv)
    output_path = Path(args.output)

    if args.check:
        return check(output_path)
    generate(output_path)
    sys.stdout.write(f"Wrote {output_path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
